spring:
  datasource:
    url: jdbc:postgresql://${DB_HOST:localhost}:${DB_PORT:5433}/${DB_NAME:formulamatch}
    username: ${DB_USER:formulamatch}
    password: ${DB_PASSWORD:formulamatch}
  jpa:
    hibernate:
      ddl-auto: validate

springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
    path: /swagger-ui.html

server:
  port: 8080
